//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKSI.Olympiad.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int DogovorId { get; set; }
        public int HotelId { get; set; }
        public int CliendId { get; set; }
        public System.DateTime DogovorDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
