//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKSI.Olympiad.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MigrationCard
    {
        public int ClientId { get; set; }
        public int CardNumber { get; set; }
        public string WhereCountry { get; set; }
        public System.DateTime StayWith { get; set; }
        public System.DateTime StayBy { get; set; }
        public string TripPurpose { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
