//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKSI.Olympiad.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int ClientId { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Address { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
